name: Run Azure Login with OIDC
on: [push]

permissions:
  id-token: write
  contents: read
jobs: 
  deploy-non-prod:
    runs-on: ubuntu-latest
    environment: NonProd
    steps:
      - run: echo deploying to Non Prod
      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: 'Run az commands'
        run: |
          az resource list 
  deploy-prod:
    runs-on: ubuntu-latest
    environment: Prod
    needs: deploy-non-prod
    steps:
      - run: echo deploying to Prod
      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: 'Run az commands'
        run: |
          az resource list 
