name: Run Azure Login with OIDC
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
jobs: 
  deploy-non-prod:
    runs-on: ubuntu-latest
    environment: NonProd
    steps:
      - run: echo deploying to Non Prod
      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: 'Run az commands'
        run: |
          az resource list --resource-name ODICDEMO-NonProd | ConvertFrom-Json | SELECT -property name
  deploy-prod:
    runs-on: ubuntu-latest
    environment: Prod
    needs: deploy-non-prod
    steps:
      - run: echo deploying to Prod
      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: 'Run az commands'
        run: |
          az resource list --resource-name ODICDEMO-Prod | ConvertFrom-Json | SELECT -property name
      - name: 'Run az commands that should return nothing'
        run: |
          az resource list --resource-name ODICDEMO-NonProd | ConvertFrom-Json | SELECT -property name
